# Generated by Django 4.2.9 on 2024-01-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sender_mail', models.CharField(max_length=150)),
                ('receipts_mail', models.CharField(max_length=150)),
                ('attachment', models.BinaryField()),
                ('attachment_name', models.CharField(max_length=150)),
            ],
        ),
    ]
