# Generated by Django 4.2.9 on 2024-01-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_mail_app', '0002_alter_baseemail_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseemail',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseemail',
            name='attachment',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
